################################
# Dockerfile: nubes/ttf-mscorefonts-debian:latest

# Base
FROM debian:latest

RUN [ "/bin/sed", "-i", "-e", "s/ main$/ main contrib/", "/etc/apt/sources.list.d/debian.sources" ]

